name: qt-framework-sdk
base: core22
version: 5.15.10
summary: Qt Framework SDK
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

parts:
  qt5:
    plugin: nil
    source: https://code.qt.io/qt/qt5.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION-lts-lgpl
    source-submodules: []
    override-pull: |
      craftctl default
      perl init-repository
    build-packages:
      - python3-minimal
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
      - libfontconfig1-dev
      - libfreetype6-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-keysyms1-dev
      - libxcb-image0-dev
      - libxcb-shm0-dev
      - libxcb-icccm4-dev
      - libxcb-sync0-dev
      - libxcb-xfixes0-dev
      - libxcb-shape0-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-xinerama0-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libwayland-dev
      - libwayland-egl1-mesa
      - libwayland-server0
      - libgles2-mesa-dev
      - libxkbcommon-dev
      - gperf
      - clang
      - bison
      - flex
      - nodejs
      - python2-minimal
      - python-pip
      - libnss3-dev
      - libdbus-1-dev
      - libdrm-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxtst-dev
      - perl
      - qt5-qmake
      - wget
      - libxdamage-dev
      - libxrandr-dev
      - libxcb-dri3-dev
    override-build: |
      cd $CRAFT_PART_SRC/qtwebengine/src/3rdparty
      git reset --hard
      wget https://raw.githubusercontent.com/meta-qt5/meta-qt5/2a38fca150f065f869ed530fffe1a07beec80692/recipes-qt/qt5/qtwebengine/chromium/0013-chromium-breakpad-fix-build-with-glibc-2.34.patch
      git apply ./0013-chromium-breakpad-fix-build-with-glibc-2.34.patch
      sed -i '1s/^/#include <limits>\n/' chromium/third_party/perfetto/src/trace_processor/containers/string_pool.h
      cd $CRAFT_PART_BUILD
      $CRAFT_PART_SRC/configure -opensource -nomake examples -nomake tests -confirm-license -prefix $CRAFT_PART_INSTALL
      cd $CRAFT_PART_BUILD
      gmake
      gmake install
      mkdir -p $CRAFT_PART_INSTALL/etc/$CRAFT_PART_NAME
      cp $CRAFT_PART_BUILD/config.summary $CRAFT_PART_INSTALL/etc/$CRAFT_PART_NAME/
    organize:
      lib: usr/lib/$CRAFT_ARCH_TRIPLET
      libexec: usr/lib/$CRAFT_ARCH_TRIPLET/qt5/libexec
      bin: usr/lib/$CRAFT_ARCH_TRIPLET/qt5/bin
      include: usr/include/$CRAFT_ARCH_TRIPLET/qt5
      plugins: usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins
      qml: usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml
      translations: usr/share/qt5/translations
      phrasebooks: usr/share/qt5/phrasebooks
      mkspecs: usr/lib/$CRAFT_ARCH_TRIPLET/qt5/mkspecs
      doc: usr/share/qt5/doc
      resources: usr/share/qt5/resources
