name: qt-framework-sdk
base: core22
version: 6.4.3
summary: Qt Framework SDK
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

parts:
  mesa:
    after: []
    plugin: nil
    build-attributes:
    - no-patchelf
    build-packages: []
    stage-packages:
    - libgl1-mesa-dri
    - libglx-mesa0
    prime:
    - -lib/udev
    - -usr/doc
    - -usr/doc-base
    - -usr/share/applications
    - -usr/share/apport
    - -usr/share/bug
    - -usr/share/doc
    - -usr/share/doc-base
    - -usr/share/icons
    - -usr/share/libdrm
    - -usr/share/libwacom
    - -usr/share/lintian
    - -usr/share/man
    - -usr/share/pkgconfig
  build-deps:
    plugin: nil
    build-packages:
      # ALL
      - python3-minimal
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
      - libfontconfig1-dev
      - libfreetype6-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-keysyms1-dev
      - libxcb-image0-dev
      - libxcb-shm0-dev
      - libxcb-icccm4-dev
      - libxcb-sync0-dev
      - libxcb-xfixes0-dev
      - libxcb-shape0-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-xinerama0-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libwayland-dev
      - libwayland-egl1-mesa
      - libwayland-server0
      - libgles2-mesa-dev
      - libxkbcommon-dev
      - gperf
      - clang
      - bison
      - flex
      - nodejs
      - python2-minimal
      - python-pip
      - libnss3-dev
      - libdbus-1-dev
      - libdrm-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxtst-dev
      # 6.4
      - clang
      - libmd4c-dev
      - libmd4c-html0-dev
      - llvm-dev
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libx11-6
      - libx11-xcb1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrender1
      - libxcb1
      - libxcb-glx0
      - libxcb-keysyms1
      - libxcb-image0
      - libxcb-shm0
      - libxcb-icccm4
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-shape0
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-xinerama0
      - libxkbcommon0
      - libxkbcommon-x11-0
  qt-framework:
    after: [build-deps, mesa]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-submodules:
      - qt3d
      - qt5compat
      - qt6-build
      - qtactiveqt
      - qtbase
      - qtcanvas3d
      - qtcharts
      - qtcoap
      - qtconnectivity
      - qtdatavis3d
      - qtdeclarative
      - qtdoc
      - qtfeedback
      - qtgamepad
      - qthttpserver
      - qtimageformats
      - qtlanguageserver
      # - qtlocation
      - qtlottie
      - qtmqtt
      - qtmultimedia
      - qtnetworkauth
      - qtopcua
      - qtpim
      - qtpositioning
      - qtqa
      - qtquick3d
      - qtquick3dphysics
      - qtquicktimeline
      - qtremoteobjects
      - qtrepotools
      - qtscxml
      - qtsensors
      - qtserialbus
      - qtserialport
      - qtshadertools
      - qtspeech
      - qtsvg
      - qtsystems
      - qttools
      - qttranslations
      - qtvirtualkeyboard
      - qtwayland
      - qtwebchannel
      - qtwebengine
      - qtwebglplugin
      - qtwebsockets
      - qtwebview
      - qtxmlpatterns
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
